services:
  localgpt:
    runtime: nvidia
    image: localgpt:latest

    container_name: localgpt_app

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8501:8501"

    volumes:
      - ./localGPT_UI.py:/app/localGPT_UI.py
      - ~/.cache:/root/.cache
      - ./SOURCE_DOCUMENTS:/app/SOURCE_DOCUMENTS
      - ./localGPT_app:/app/localGPT_app
      - ./config:/app/config
      - ./DB:/app/DB
    working_dir: /app                               # Thiết lập thư mục làm việc là /app

    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=false
      - STREAMLIT_BROWSER_GATHERUSAGESTATS=false
      - CUDA_VISIBLE_DEVICES=0


